# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(help_text="'-' 를 제외한 숫자만 입력", max_length=20),
        ),
    ]
