# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170823_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', help_text='실명 입력을 권장합니다.', max_length=20),
            preserve_default=False,
        ),
    ]
