# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='flower/', verbose_name='FloImg')),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flower',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='floimg',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Flower'),
        ),
    ]
