# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_flower_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=100, verbose_name='꽃 이름'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='flower/thumbnail', verbose_name='썸네일'),
        ),
    ]
