# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170822_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flower',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='flower',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
    ]
