# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170822_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='is_best',
            field=models.BooleanField(default=False, verbose_name='베스트'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='thumbnail',
            field=models.ImageField(upload_to='flower/thumbnail', verbose_name='썸네일'),
        ),
    ]
