# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20170825_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Flower')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flower',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='shop.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
