# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_auto_20170827_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(default=shop.models._createHash, max_length=100, unique=True)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone_number', models.CharField(max_length=11)),
                ('receiver_email', models.EmailField(max_length=100)),
                ('receiver_post_code', models.CharField(max_length=10)),
                ('receiver_address', models.CharField(max_length=50)),
                ('receiver_address_detail', models.CharField(max_length=50)),
                ('flower_id', models.CharField(max_length=100)),
                ('flower_count', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
