# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
