# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Flower')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='flower_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flower_id',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order'),
        ),
    ]
