# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170829_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='flower',
            name='image01',
            field=models.ImageField(blank=True, upload_to='flower/images', verbose_name='이미지01'),
        ),
        migrations.AddField(
            model_name='flower',
            name='image02',
            field=models.ImageField(blank=True, upload_to='flower/images', verbose_name='이미지02'),
        ),
        migrations.AddField(
            model_name='flower',
            name='image03',
            field=models.ImageField(blank=True, upload_to='flower/images', verbose_name='이미지03'),
        ),
        migrations.AddField(
            model_name='flower',
            name='image04',
            field=models.ImageField(blank=True, upload_to='flower/images', verbose_name='이미지04'),
        ),
        migrations.AddField(
            model_name='flower',
            name='image05',
            field=models.ImageField(blank=True, upload_to='flower/images', verbose_name='이미지05'),
        ),
    ]
