# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20170830_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentqa',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='commentqa',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
