# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170830_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentqa',
            name='image01',
            field=models.ImageField(blank=True, upload_to='commentqa/images', verbose_name='이미지01'),
        ),
        migrations.AddField(
            model_name='commentqa',
            name='image02',
            field=models.ImageField(blank=True, upload_to='commentqa/images', verbose_name='이미지02'),
        ),
    ]
